version: "3"
services:
  bitcoind:
    image: fractalbitcoin/fractal:v0.2.1
    entrypoint: ["bitcoind", "-datadir=/data/", "-maxtipage=504576000"]
    command: ""
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-datadir=/data/", "getblockchaininfo"]
    networks:
      - fractal-bitcoin
    ports:
      - "8333:8333"
    deploy:
      resources:
        limits:
          memory: 40G
    memswap_limit: 60G
    mem_swappiness: 100
    volumes:
      - ./data:/data
    logging:
      driver: "json-file"
      options:
        labels: "env,filebeat,name"
        max-size: "1g"
        max-file: "3"
networks:
  fractal-bitcoin:
